Repository wso2-extensions/identity-event-handler-notification, pull requests merged in 2020-02, with the labels that each got.

#114 Adding SMS notification templates to the registry on server startup and tenant creation
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/EmailTemplateManagerImpl.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/constants/I18nMgtConstants.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/exceptions/I18nEmailMgtInternalException.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/internal/I18nMgtServiceComponent.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/internal/TenantManagementListener.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/util/I18nEmailUtil.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/test/java/org/wso2/carbon/email/mgt/EmailTemplateManagerImplTest.java
  components/email-mgt/org.wso2.carbon.email.mgt/src/test/resources/email/email-admin-config.xml
  components/email-mgt/org.wso2.carbon.email.mgt/src/test/resources/sms/sms-templates-admin-config.xml
  features/org.wso2.carbon.email.mgt.server.feature/pom.xml
  features/org.wso2.carbon.email.mgt.server.feature/resources/p2.inf
  features/org.wso2.carbon.email.mgt.server.feature/resources/sms-templates-admin-config.xml
  pom.xml
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, Integration-Test-Suite/ Pending

#113 Adding a default notification template for email verification on update
  features/org.wso2.carbon.email.mgt.server.feature/resources/email-admin-config.xml
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#118 Adding resend SMS confirmation template
  components/email-mgt/org.wso2.carbon.email.mgt/src/test/resources/sms/sms-templates-admin-config.xml
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending

#117 Add emailOTP template to email-admin-config file
  features/org.wso2.carbon.email.mgt.server.feature/resources/email-admin-config.xml
Labels: Approval/Pending, Code-Quality-Review/Done, Functionality-Review/Done
